### ISSUE TITLE
Thumbs carousel configuration

### ISSUE THREAD

**Issue by jpgutti** [vtex-apps/store-components#371] opened 2019-03-18 18:07 UTC
**Is your feature request related to a problem? Please describe.**
I need to add arrows to the vertical thumbs carousel but it can't be achieved since you guys use the swiper lib and have set up a static config object inside the component.

**Describe the solution you'd like**
Make it possible to control the swiper carousel configuration by props in the blocks, adding all the remaining properties that the lib can have.

**Comment by juliomoreira** [comment] 2019-07-19 17:48
Duplicate of https://github.com/vtex-apps/store-discussion/issues/57

**Comment by lbebber** [comment] 2019-07-23 18:43
We do not intend on exposing all the Swiper configs from our component (because, for example, we might change the implementation and not use Swiper anymore, or the prop might not make sense to be exported, etc).

However, adding arrows on the thumbnails makes sense; PR https://github.com/vtex-apps/store-components/pull/531 does that.

**Closed by lbebber** 2019-07-23 18:43 UTC
